### Health
GET http://localhost:3000/health

### Login (Obter Token)
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### Guardar o token da resposta anterior
@token = {{login.response.body.token}}

### Listar minhas requests (Protegido)
GET http://localhost:3000/requests
Authorization: Bearer {{token}}

### Criar request (Protegido)
POST http://localhost:3000/requests
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "day-off",
  "startDate": "2026-04-07",
  "endDate": "2026-04-13"
}

### Criar request
POST http://localhost:3000/requests
Content-Type: application/json

{
  "type": "day-off",
  "startDate": "2026-03-07",
  "endDate": "2026-03-13"
}

### Criar user
POST http://localhost:3000/users
Content-Type: application/json

{
  "nome": "Mateus Gomes",
  "email": "[EMAIL_ADDRESS]",
  "password": "[PASSWORD]",
  "role": "admin"
}

### Alterar status da request
PUT http://localhost:3000/requests/89b7302d-f714-4604-8a92-8c43c35093b8
Content-Type: application/json

{
  "status": "APPROVED"
}

### Buscar request específica
GET http://localhost:3000/requests/1f9e4e37-d8c0-40d5-90ca-3fdec9bc4910

### Listar histórico da request
GET http://localhost:3000/requests/00000000-0000-0000-0000-000000000001/history

### Listar minhas requests
GET http://localhost:3000/requests

### Listar users
GET http://localhost:3000/users

### Filtrar por status
GET http://localhost:3000/requests?status=DRAFT

### Deletar request
DELETE http://localhost:3000/requests/df9f5d1b-cea1-4132-bea8-6f48f2a1411b
Authorization: Bearer {{token}}

### Deletar user
DELETE http://localhost:3000/users/475f589c-34ce-47d0-aa1f-62cc4729d8fc
Authorization: Bearer {{token}}

### Recarregar o saldo de todos os usuários
POST http://localhost:3000/users/reload-all-balances